export const SHIPMENTS_LOAD_START = 'SHIPMENTS_LOAD_START';
export const SHIPMENTS_LOAD_SUCCESS = 'SHIPMENTS_LOAD_SUCCESS';
export const SHIPMENTS_LOAD_FAIL = 'SHIPMENTS_LOAD_FAIL';
export const SHIPMENTS_ADD_START = 'SHIPMENTS_ADD_START';
export const SHIPMENTS_ADD_SUCCESS = 'SHIPMENTS_ADD_SUCCESS';
export const SHIPMENTS_ADD_FAIL = 'SHIPMENTS_ADD_FAIL';
export const SHIPMENTS_EDIT_START = 'SHIPMENTS_EDIT_START';
export const SHIPMENTS_EDIT_SUCCESS = 'SHIPMENTS_EDIT_SUCCESS';
export const SHIPMENTS_EDIT_FAIL = 'SHIPMENTS_EDIT_FAIL';
export const SHIPMENTS_REMOVE_START = 'SHIPMENTS_REMOVE_START';
export const SHIPMENTS_REMOVE_SUCCESS = 'SHIPMENTS_REMOVE_SUCCESS';
export const SHIPMENTS_REMOVE_FAIL = 'SHIPMENTS_REMOVE_FAIL';
export const SHIPMENTS_DATA_CHANGED_NOTIFICATION_SHOWN = 'SHIPMENTS_DATA_CHANGED_NOTIFICATION_SHOWN';

